export const stats = [
  { label: "Years Behind the Bar", value: "4+", detail: "Expérience" },
  { label: "Establishments", value: "35+", detail: "Bars & restaurants" },
  { label: "Specialties", value: "Classiques & mixologie", detail: "Cocktails" },
  { label: "Locations", value: "Paris & Île-de-France", detail: "Mobile, nuit" },
];

export const qualifications = [
  "Barman",
  "Serveur",
  "Barman mixologue",
  "Barman cocktail",
  "Barista",
  "Chef de rang",
];

export const skills = [
  "Cocktails de base",
  "Création de cocktails",
  "Mixologie",
  "Service au plateau",
  "Service client",
  "Service au comptoir",
  "Encaissement",
  "Compétences administratives",
  "Cocktails avancés",
  "Service à l'assiette",
  "Barista",
  "Gestion du bar",
  "Portage de plateau",
  "Débarassage des tables",
  "Hygiène et sécurité",
];

export const languages = ["Anglais", "Français", "Népalais", "Espagnol", "Hindi"];

export const experiences = [
  {
    period: "12/2025",
    role: "Barman",
    establishment: "Biche",
    type: "Brasserie chic",
    location: "Paris 75008",
    contract: "Extra",
  },
  {
    period: "11/2025",
    role: "Barman",
    establishment: "Splash (salle)",
    type: "Néo-bistrot",
    location: "Asnières-sur-Seine 92600",
    contract: "Extra",
  },
  {
    period: "11/2025",
    role: "Barman",
    establishment: "Bouillon de Paris",
    type: "Café - restaurant",
    location: "Paris 75003",
    contract: "Extra",
  },
  {
    period: "11/2025",
    role: "Barman",
    establishment: "Café A (salle)",
    type: "Café - restaurant",
    location: "Paris 75010",
    contract: "Extra",
  },
  {
    period: "10/2025",
    role: "Barman",
    establishment: "Square",
    type: "Bar",
    location: "Paris 75008",
    contract: "Extra",
  },
  {
    period: "09/2025",
    role: "Barman",
    establishment: "Restaurant / Room Service Hôtel Fauchon",
    type: "Hôtel *****",
    location: "Paris 75008",
    contract: "Extra",
  },
  {
    period: "09/2025",
    role: "Barman",
    establishment: "Jungle Palace",
    type: "Restaurant - bar",
    location: "Paris 75010",
    contract: "Extra",
  },
  {
    period: "08/2025",
    role: "Barman",
    establishment: "Prost",
    type: "Bar - restaurant",
    location: "Paris 75004",
    contract: "Extra",
  },
  {
    period: "06/2025",
    role: "Barman",
    establishment: "Victoria Palace",
    type: "Hôtel ****",
    location: "Paris 75006",
    contract: "Extra",
  },
  {
    period: "06/2025",
    role: "Barman",
    establishment: "Rex Club",
    type: "Bar - club",
    location: "Paris 75002",
    contract: "Extra",
  },
  {
    period: "06/2025",
    role: "Barman mixologue",
    establishment: "Suelo",
    type: "Brasserie chic",
    location: "Paris 75008",
    contract: "Extra",
  },
  {
    period: "01/2025",
    role: "Barman",
    establishment: "Bleu Coupole Printemps Haussmann (salle)",
    type: "Brasserie chic",
    location: "Paris 75009",
    contract: "Extra",
  },
  {
    period: "01/2025",
    role: "Barman",
    establishment: "Stellar",
    type: "Restaurant - bar",
    location: "Paris 75011",
    contract: "Extra",
  },
  {
    period: "12/2024",
    role: "Barman",
    establishment: "SAS Le Diamant Bleu",
    type: "Restaurant gastronomique",
    location: "Ivry-sur-Seine 94200",
    contract: "Extra",
  },
  {
    period: "12/2024",
    role: "Barista",
    establishment: "Café du Palais",
    type: "Café - restaurant",
    location: "Paris 75116",
    contract: "Extra",
  },
  {
    period: "12/2024",
    role: "Barman",
    establishment: "Paillettes",
    type: "Bar - club",
    location: "Paris 75002",
    contract: "Extra",
  },
  {
    period: "10/2024",
    role: "Barman cocktail",
    establishment: "Le Patio Opéra",
    type: "Restaurant bistronomique",
    location: "Paris 75009",
    contract: "Extra",
  },
  {
    period: "09/2024 – 10/2024",
    role: "Barman",
    establishment: "Club Cochon L'Auberge",
    type: "Restaurant - bar",
    location: "Paris 75009",
    contract: "Extra",
  },
  {
    period: "09/2024",
    role: "Barman",
    establishment: "The Little Italy",
    type: "Restaurant italien",
    location: "Paris 75017",
    contract: "Extra",
  },
  {
    period: "08/2024",
    role: "Barman",
    establishment: "Atica",
    type: "Restaurant gastronomique",
    location: "Paris 75005",
    contract: "Extra",
  },
  {
    period: "08/2024",
    role: "Barman",
    establishment: "Le Florès",
    type: "Brasserie",
    location: "Paris 75007",
    contract: "Extra",
  },
  {
    period: "08/2024",
    role: "Barman",
    establishment: "La Marbrerie",
    type: "Salle de concert",
    location: "Montreuil 93100",
    contract: "Extra",
  },
  {
    period: "08/2024",
    role: "Barman",
    establishment: "L’Absinthe",
    type: "Café - bar",
    location: "Paris 75003",
    contract: "Extra",
  },
  {
    period: "08/2024",
    role: "Barman",
    establishment: "Café Joséphine",
    type: "Brasserie chic",
    location: "Paris 75001",
    contract: "Extra",
  },
  {
    period: "08/2024",
    role: "Barman",
    establishment: "The Brooklyn Pizzeria",
    type: "Pizzeria",
    location: "Paris 75003",
    contract: "Extra",
  },
  {
    period: "08/2024",
    role: "Barman",
    establishment: "Enza Famiglia Louvre (salle)",
    type: "Restaurant italien",
    location: "Paris 75001",
    contract: "Extra",
  },
  {
    period: "07/2024",
    role: "Barman",
    establishment: "Terrass Hotel (salle)",
    type: "Restaurant d'hôtel",
    location: "Paris 75018",
    contract: "Extra",
  },
  {
    period: "07/2024",
    role: "Barman",
    establishment: "Hôtel Particulier Montmartre (salle)",
    type: "Hôtel *****",
    location: "Paris 75018",
    contract: "Extra",
  },
  {
    period: "03/2024",
    role: "Barman",
    establishment: "Le Magnifique",
    type: "Brasserie chic",
    location: "Paris 75008",
    contract: "Extra",
  },
  {
    period: "03/2024",
    role: "Barman",
    establishment: "Kubri",
    type: "Concept food",
    location: "Paris 75011",
    contract: "Extra",
  },
  {
    period: "02/2024",
    role: "Barman",
    establishment: "Lombem",
    type: "Café - restaurant",
    location: "Paris 75002",
    contract: "Extra",
  },
  {
    period: "02/2024",
    role: "Barman",
    establishment: "Le Patio Opéra",
    type: "Restaurant bistronomique",
    location: "Paris 75009",
    contract: "Extra",
  },
  {
    period: "01/2024",
    role: "Barman",
    establishment: "Soho",
    type: "Restaurant italien",
    location: "Paris 75005",
    contract: "Extra",
  },
  {
    period: "12/2023",
    role: "Barman",
    establishment: "La Petite Halle",
    type: "Restaurant - bar",
    location: "Paris 75019",
    contract: "Extra",
  },
  {
    period: "12/2023",
    role: "Barman mixologue",
    establishment: "La Boîte à Cocktails",
    type: "Événementiel",
    location: "Paris 75002",
    contract: "Extra",
  },
  {
    period: "12/2023",
    role: "Barman",
    establishment: "Barolo",
    type: "Café - restaurant",
    location: "Joinville-le-Pont 94340",
    contract: "Extra",
  },
  {
    period: "11/2023",
    role: "Barman",
    establishment: "Restaurant L’Alma",
    type: "Brasserie chic",
    location: "Paris 75007",
    contract: "Extra",
  },
  {
    period: "10/2023",
    role: "Barman",
    establishment: "Les Trois Hiboux",
    type: "Événementiel",
    location: "Plailly 60128",
    contract: "Extra",
  },
  {
    period: "09/2023",
    role: "Serveur",
    establishment: "Les Empotés (service)",
    type: "Traiteur",
    location: "Nanterre 92000",
    contract: "Extra",
  },
  {
    period: "09/2023",
    role: "Barman",
    establishment: "Quartier Vavin",
    type: "Café - restaurant",
    location: "Paris 75006",
    contract: "Extra",
  },
  {
    period: "09/2023",
    role: "Barman",
    establishment: "Villa Mikuna",
    type: "Brasserie chic",
    location: "Paris 75009",
    contract: "Extra",
  },
  {
    period: "06/2023 – 09/2023",
    role: "Barman",
    establishment: "Café du Trocadéro",
    type: "Café - restaurant",
    location: "Paris 75016",
    contract: "CDD",
  },
  {
    period: "06/2023",
    role: "Barman",
    establishment: "Summer Act",
    type: "Bar",
    location: "Paris 75011",
    contract: "Saisonnier",
  },
  {
    period: "05/2023",
    role: "Barman",
    establishment: "Café Carrousel",
    type: "Café - restaurant",
    location: "Paris 75001",
    contract: "CDD",
  },
  {
    period: "02/2023 – 03/2023",
    role: "Barman",
    establishment: "Bazturo",
    type: "Bar - restaurant",
    location: "Paris 75006",
    contract: "Extra",
  },
  {
    period: "02/2023 – 05/2023",
    role: "Barman",
    establishment: "Le Biscornu",
    type: "Bar - club",
    location: "Paris 75002",
    contract: "Extra",
  },
  {
    period: "03/2022 – 02/2023",
    role: "Barman",
    establishment: "Le Verre Siffleur",
    type: "Autres",
    location: "Paris 75014",
    contract: "CDI",
  },
  {
    period: "07/2021 – 02/2022",
    role: "Chef de rang",
    establishment: "Salamnamaste",
    type: "Restaurant chic",
    location: "Créteil 94000",
    contract: "CDI",
  },
  {
    period: "02/2020 – 06/2021",
    role: "Barman",
    establishment: "Jardin du Prince",
    type: "Restaurant asiatique",
    location: "Créteil 94000",
    contract: "Extra",
  },
];

